### ISSUE TITLE
Array::Iterator dies if passed a single element

### ISSUE THREAD

**Issue by pwr22** [perlancar/perl-Array-Iterator#4]
It gives off this exception

    Incorrect Type : the argument must be an array or hash reference at C:/Strawberry/perl/site/lib/Array/Iterator.pm line 28.

I think that branch of the validation if should actually be assuming the one arg it got is the one thing to iterate over (makes more sense in the `::Circular` subclass)

**Comment by pwr22** [comment]
Heres some code which shows the issue

```perl
use Array::Iterator;
my @array = qw( one_element );
my $iterator = Array::Iterator->new(@array); # dies
```

**Comment by perlancar** [comment]
Sorry for the very late response. I didn't see the notification for this issue.

I've removed the check (commit 653be64). Passing a list of length 0 or 1 still makes sense to me.
